#version 460 core

layout (local_size_x = 16, local_size_y = 8, local_size_z = 1) in;

layout (r32ui, binding = 0) writeonly restrict uniform uimage2D destination;
layout (r32ui, binding = 1) readonly restrict uniform uimage2D source;
layout (r8ui, binding = 2) writeonly restrict uniform uimage2D changedFlagTexture;
layout (std430, binding = 3) readonly restrict buffer startBuffer {
    uint[] startPositions;
};

uniform int mask;
uniform int generationCount;

struct Region {
    uint topLeft;
    uint top;
    uint topRight;
    uint left;
    uint center;
    uint right;
    uint bottomLeft;
    uint bottom;
    uint bottomRight;
};

uint valueAt(ivec2 position) {
    return imageLoad(source, position & ivec2(mask >> 2, mask >> 3)).r;
}

Region sampleRegion(ivec2 texelCoord) {
    uint topLeft = valueAt(texelCoord + ivec2(-1, 1));
    uint top = valueAt(texelCoord + ivec2(0, 1));
    uint topRight = valueAt(texelCoord + ivec2(1, 1));

    uint left = valueAt(texelCoord + ivec2(-1, 0));
    uint center = valueAt(texelCoord);
    uint right = valueAt(texelCoord + ivec2(1, 0));

    uint bottomLeft = valueAt(texelCoord + ivec2(-1, -1));
    uint bottom = valueAt(texelCoord + ivec2(0, -1));
    uint bottomRight = valueAt(texelCoord + ivec2(1, -1));

    return Region(topLeft, top, topRight, left, center, right, bottomLeft, bottom, bottomRight);
}

uint getFromBlock(uint block, int x, int y) {
    return block >> (y << 2 | x & 3) & 1;
}

uint getFromRegion(Region region, int x, int y) {
    if (x < 0) {
        if (y < 0) return getFromBlock(region.bottomLeft, x, y);
        if (y >= 8) return getFromBlock(region.topLeft, x, y);
        return getFromBlock(region.left, x, y);
    }

    if (x >= 4) {
        if (y < 0) return getFromBlock(region.bottomRight, x, y);
        if (y >= 8) return getFromBlock(region.topRight, x, y);
        return getFromBlock(region.right, x, y);
    }

    if (y < 0) return getFromBlock(region.bottom, x, y);
    if (y >= 8) return getFromBlock(region.top, x, y);
    return getFromBlock(region.center, x, y);
}

uint storeIntoBlock(uint block, int x, int y) {
    return block | 1 << (y << 2 | x & 3);
}

void storeIntoRegion(inout Region region, int x, int y) {
    if (x < 0) {
        if (y < 0) region.bottomLeft = storeIntoBlock(region.bottomLeft, x, y);
        else if (y >= 8) region.topLeft = storeIntoBlock(region.topLeft, x, y);
        else region.left = storeIntoBlock(region.left, x, y);
    }
    else if (x >= 4) {
        if (y < 0) region.bottomRight = storeIntoBlock(region.bottomRight, x, y);
        else if (y >= 8) region.topRight = storeIntoBlock(region.topRight, x, y);
        else region.right = storeIntoBlock(region.right, x, y);
    }
    else {
        if (y < 0) region.bottom = storeIntoBlock(region.bottom, x, y);
        else if (y >= 8) region.top = storeIntoBlock(region.top, x, y);
        else region.center = storeIntoBlock(region.center, x, y);
    }
}

void main() {
    uint chunkPosition = startPositions[gl_WorkGroupID.x];
    ivec2 texelCoord = ivec2((chunkPosition >> 16) << 4, (chunkPosition & 0xFFFF) << 3) + ivec2(gl_LocalInvocationID.xy);
    Region sourceRegion = sampleRegion(texelCoord);
    Region destinationRegion = Region(0, 0, 0, 0, 0, 0, 0, 0, 0);
    uint orginal = sourceRegion.center;

    int count = clamp(generationCount, 1, 4);
    for (int generation = count - 1; generation >= 0; generation--) {
        for (int y = -generation; y < 8 + generation; y++) {
            for (int x = -generation; x < 4 + generation; x++) {
                uint counter = getFromRegion(sourceRegion, x, y) << 4;

                counter += getFromRegion(sourceRegion, x - 1, y + 1);
                counter += getFromRegion(sourceRegion, x + 0, y + 1);
                counter += getFromRegion(sourceRegion, x + 1, y + 1);

                counter += getFromRegion(sourceRegion, x - 1, y + 0);
                counter += getFromRegion(sourceRegion, x + 1, y + 0);

                counter += getFromRegion(sourceRegion, x - 1, y - 1);
                counter += getFromRegion(sourceRegion, x + 0, y - 1);
                counter += getFromRegion(sourceRegion, x + 1, y - 1);

                if (bool(0xC0008 >> counter & 1)) storeIntoRegion(destinationRegion, x, y);
            }
        }
        sourceRegion = destinationRegion;
        destinationRegion = Region(0, 0, 0, 0, 0, 0, 0, 0, 0);
    }
    uint result = sourceRegion.center;
    imageStore(destination, texelCoord, uvec4(result));
    if (result != orginal) imageStore(changedFlagTexture, ivec2(chunkPosition >> 16, chunkPosition & 0xFFFF), uvec4(1));
}